import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Layout from "../components/layout";
import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/router";
import { faPlus, faSearch, faUser } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useSockets } from "../context/socket.context";
import { customAlphabet } from "nanoid";
import Link from "next/link";
import EVENTS from "../config/events";

export default function Home() {
  const { socket, username, setUsername, lobbyId, lobbys } = useSockets();
  const newLobbyRef = useRef<HTMLInputElement>(null);
  const usernameRef = useRef<HTMLInputElement>();
  const router = useRouter();
  const [search, setSearch] = useState("");


  const handleUsername = async () => {
    const name = usernameRef.current.value;
    setUsername(name);
    if (!name) {
      return;
    }
    console.log('setting username in sessionstorage');
    sessionStorage.setItem("username", name);
  };

  const handleCreateRoom = () => {
    var lobbyName;
    if (!String(newLobbyRef.current.value).trim()) {
      const nanoid = customAlphabet("0123456789", 6);
      lobbyName = nanoid();
    } else {
      lobbyName = newLobbyRef.current.value || "";
    }
    socket.emit(EVENTS.CLIENT.CREATE_LOBBY, { lobbyName, username });
  };


  const handleJoinRoom = (key) => {
    if (key === lobbyId) return;
    router.push(`/lobby/${key}`);
  };

  useEffect(() => {
    if (usernameRef.current) {
      usernameRef.current.value = sessionStorage.getItem("username") || "";
    }
    socket.on(EVENTS.SERVER.JOINED_LOBBY, ({ lobbyId, players }) => {
      router.push(`/lobby/${lobbyId}`);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Secret Santa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>Welcome {username} to the Secret santa</h1>
          <Image
            src="/christmas-tree.png"
            alt="Secret Santa"
            width={200}
            height={200}
          />
          {!username ? (
            <div className={styles.input}>
              <input
                ref={usernameRef}
                onKeyDown={(event) => {
                  event.key === "Enter" ? handleUsername() : {};
                }}
                placeholder="rudolph"
              ></input>
              <p onClick={handleUsername}>
                <FontAwesomeIcon icon={faUser} />
              </p>
            </div>
          ) : (
            <>
              <h3>Join here</h3>
              <div className={styles.input}>
                <input
                  value={search}
                  onKeyDown={(event) => {
                    event.key === "Enter" ? handleJoinRoom(search) : {};
                  }}
                  placeholder="123456"
                  onChange={(e) => setSearch(e.target.value)}
                ></input>
                <p onClick={() => handleJoinRoom(search)}>
                  <FontAwesomeIcon icon={faSearch} />
                </p>
              </div>
              <h3>Create Lobby</h3>
              <div className={styles.input}>
                <input
                  ref={newLobbyRef}
                  onKeyDown={(event) => {
                    event.key === "Enter" ? handleCreateRoom() : {};
                  }}
                  placeholder="abcdefu"
                />
                <p onClick={() => handleCreateRoom()}>
                  <FontAwesomeIcon icon={faPlus} />
                </p>
              </div>
            </>
          )}
        </main>
      </Layout>
    </>
  );
}
