import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Layout from "../components/layout";
import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/router";
import { faSearch, faUser } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useSockets } from "../context/socket.context";
// import
import Link from "next/link";

export default function Home() {
  const { socket, username, setUsername } = useSockets();
  const usernameRef = useRef(null);
  const router = useRouter();
  const [search, setSearch] = useState("");

  const enterRoom = (id: string) => {
    router.push(`/lobby/${id}`);
  };

  const handleUsername = () => {
    const name = usernameRef.current.value;

    if (!name) {
      return;
    }

    setUsername(name);
    localStorage.setItem("username", name);
  };

  useEffect(() => {
    console.log(username);
    if (usernameRef)
      usernameRef.current.value = localStorage.getItem("username") || "";
  }, []);

  return (
    <>
      <Head>
        <title>Secret Santa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>Welcome to the Secret santa</h1>
          <Image
            src="/christmas-tree.png"
            alt="Secret Santa"
            width={200}
            height={200}
          />
          {
          username ? (<h1>{username}</h1>):(<h1>none</h1>)
          }
          {!username && (
            <div className={styles.input}>
              <input
                ref={usernameRef}
                onKeyDown={(event) => {
                  event.key === "Enter" ? handleUsername() : {};
                }}
                placeholder="rudolph"
              ></input>
              <p onClick={() => handleUsername()}>
                <FontAwesomeIcon icon={faUser} />
              </p>
            </div>
          )}
          {username && (
            <>
              <h3>Join here</h3>
              <div className={styles.input}>
                <input
                  value={search}
                  onKeyDown={(event) => {
                    event.key === "Enter" ? enterRoom(search) : {};
                  }}
                  onChange={(e) => setSearch(e.target.value)}
                ></input>
                <Link href="">
                  <p>
                    <FontAwesomeIcon icon={faSearch} />
                  </p>
                </Link>
              </div>
              <p>or</p>
              <div className={styles.create}>
                <Link href="">
                  <h4>Create Room</h4>
                </Link>
              </div>
            </>
          )}
        </main>
      </Layout>
    </>
  );
}
