import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Layout from '../components/layout'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/router'
import {faSearch} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Link from 'next/link'
export default function Home() {
  const router = useRouter()
  const [search,setSearch] = useState('')
  const enterRoom = (id:string) => {
    router.push(`/lobby/${id}`)
  }
  return (
    <>
      <Head>
        <title>Secret Santa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>Welcome to the Secret santa</h1>
          <Image src="/christmas-tree.png" alt="Secret Santa" width={200} height={200} />
          <h3>Join here</h3>
          <div className={styles.input}>
            <input value={search} onKeyDown={(event)=>{event.key==="Enter"? enterRoom(search):{}}} onChange={(e)=>setSearch(e.target.value)}></input>
            <Link href=""><p><FontAwesomeIcon icon={faSearch}/></p></Link>
          </div>
          <p>or</p>
          <div className={styles.create}>
            <Link href=""><h4>Create Room</h4></Link>
          </div>
        </main>
      </Layout>
    </>
  )
}
